apiVersion: v1
kind: ConfigMap
metadata:
  name: hypertube-config
  namespace: hypertube
data:
  # Database configuration
  POSTGRES_DB: "hypertube"
  POSTGRES_USER: "hypertube_user"
  
  # Redis configuration
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  
  # Spring configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/hypertube"
  SPRING_DATASOURCE_USERNAME: "hypertube_user"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8081"
  VIDEO_SERVICE_URL: "http://video-service:3002"
  
  # Video service configuration
  NODE_ENV: "production"
  REDIS_URL: "redis://redis:6379"
  POSTGRES_URL: "postgresql://hypertube_user:hypertube_password@postgres:5432/hypertube"
  STORAGE_PATH: "/app/storage"
  CLEANUP_INTERVAL: "24"
  MAX_STORAGE_SIZE: "50"
  
  # CORS configuration
  CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://localhost:3000"
  
  # JWT configuration
  JWT_EXPIRATION: "86400000"

---
apiVersion: v1
kind: Secret
metadata:
  name: hypertube-secrets
  namespace: hypertube
type: Opaque
data:
  # Base64 encoded secrets
  POSTGRES_PASSWORD: aHlwZXJ0dWJlX3Bhc3N3b3JkCg==  # hypertube_password
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9uCg==  # your-super-secret-jwt-key-change-this-in-production 