server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: hypertube-api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  cloud:
    loadbalancer:
      enabled: false
    discovery:
      enabled: false

# Configuration minimale - tout le reste est dans GatewayProperties avec des valeurs par défaut
hypertube:
  gateway:
    jwt:
      secret: ${JWT_SECRET:dev-jwt-secret-key-hypertube-development-environment-secure-256-bits}
    services:
      auth-service:
        url: ${AUTH_SERVICE_URL:http://localhost:8081}
      video-service:
        url: ${VIDEO_SERVICE_URL:http://localhost:3002}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.hypertube.gateway: ${LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: ${LOG_LEVEL:INFO}
    org.springframework.cloud.loadbalancer: WARN

---
# Profil Docker
spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis

hypertube:
  gateway:
    services:
      auth-service:
        url: http://auth-service:8081
      video-service:
        url: http://video-service:3002

---
# Profil Production
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    com.hypertube.gateway: WARN 